### ISSUE TITLE
sqlalchemy.exc.NoReferencedTableError on initial flask db migrate

### ISSUE THREAD

**Issue by louking** [louking/mysql-docker#3]
seen in WIP 2e1d8b2f6468257fae5268801797cfed82ea3c22 for louking/webmodules#10

same as louking/webmodules#26

```
(.venv) PS>> docker exec mysql-docker-shell-1 flask db migrate -m "initial create"
INFO  [alembic.env] Migrating database <default>
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
Traceback (most recent call last):
  File "/usr/local/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 1063, in main
    cli.main()
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 357, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/flask_migrate/cli.py", line 105, in migrate
    _migrate(directory, message, sql, head, splice, branch_label, version_path,
  File "/usr/local/lib/python3.9/site-packages/flask_migrate/__init__.py", line 111, in wrapped
    f(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/flask_migrate/__init__.py", line 170, in migrate
    command.revision(config, message, autogenerate=True, sql=sql,
  File "/usr/local/lib/python3.9/site-packages/alembic/command.py", line 236, in revision
    script_directory.run_env()
  File "/usr/local/lib/python3.9/site-packages/alembic/script/base.py", line 582, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/usr/local/lib/python3.9/site-packages/alembic/util/pyfiles.py", line 94, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python3.9/site-packages/alembic/util/pyfiles.py", line 110, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "migrations/env.py", line 189, in <module>
    run_migrations_online()
  File "migrations/env.py", line 169, in run_migrations_online
    context.run_migrations(engine_name=name)
  File "<string>", line 8, in run_migrations
  File "/usr/local/lib/python3.9/site-packages/alembic/runtime/environment.py", line 928, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/local/lib/python3.9/site-packages/alembic/runtime/migration.py", line 615, in run_migrations
    for step in self._migrations_fn(heads, self):
  File "/usr/local/lib/python3.9/site-packages/alembic/command.py", line 212, in retrieve_migrations
    revision_context.run_autogenerate(rev, context)
  File "/usr/local/lib/python3.9/site-packages/alembic/autogenerate/api.py", line 562, in run_autogenerate
    self._run_environment(rev, migration_context, True)
  File "/usr/local/lib/python3.9/site-packages/alembic/autogenerate/api.py", line 609, in _run_environment
    compare._populate_migration_script(
  File "/usr/local/lib/python3.9/site-packages/alembic/autogenerate/compare.py", line 59, in _populate_migration_script
    _produce_net_changes(autogen_context, upgrade_ops)
  File "/usr/local/lib/python3.9/site-packages/alembic/autogenerate/compare.py", line 93, in _produce_net_changes
    comparators.dispatch("schema", autogen_context.dialect.name)(
  File "/usr/local/lib/python3.9/site-packages/alembic/util/langhelpers.py", line 269, in go
    fn(*arg, **kw)
  File "/usr/local/lib/python3.9/site-packages/alembic/autogenerate/compare.py", line 129, in _autogen_for_tables
    [(table.schema, table.name) for table in autogen_context.sorted_tables]
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 1141, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/usr/local/lib/python3.9/site-packages/alembic/autogenerate/api.py", line 479, in sorted_tables
    result.extend(m.sorted_tables)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/schema.py", line 5585, in sorted_tables
    return ddl.sort_tables(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/ddl.py", line 1254, in sort_tables
    for (t, fkcs) in sort_tables_and_constraints(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/ddl.py", line 1330, in sort_tables_and_constraints
    dependent_on = fkc.referred_table
ql/schema.py", line 3148, in column
    return self._resolve_column()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/schema.py", line 3171, in _resolve_column
    raise exc.NoReferencedTableError(
sqlalchemy.exc.NoReferencedTableError: Foreign key associated with column 'apps_interests.interest_id' could not find table 'interest' with which to generate a foreign key to target column 'id'
```

**Comment by louking** [comment]
raised question in flask-migrate https://github.com/miguelgrinberg/Flask-Migrate/discussions/521
