### ISSUE TITLE
MySQLdb.ProgrammingError (1146, "Table 'users.user' doesn't exist")

### ISSUE THREAD

**Issue by louking** [louking/mysql-docker#4]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.9/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "/usr/local/lib/python3.9/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/usr/local/lib/python3.9/site-packages/MySQLdb/connections.py", line 255, in query
    _mysql.connection.query(self, query)
MySQLdb.ProgrammingError: (1146, "Table 'users.user' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/flask", line 8, in <module>
  File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 1063, in main
    cli.main()
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1651, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1698, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
  File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 578, in get_command
    app = info.load_app()
  File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 312, in load_app
    app = locate_app(import_name, None, raise_if_not_found=False)
  File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 218, in locate_app
    __import__(module_name)
  File "/app/app.py", line 28, in <module>
    app = create_app(Production(configfiles), configfiles, init_for_operation=False)
  File "/app/mysql_docker/__init__.py", line 96, in create_app
    users = User.query.all()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2773, in all
    return self._iter().all()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2916, in _iter
    result = self.session.execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1714, in execute
er AS user_fs_uniquifier, user.confirmed_at AS user_confirmed_at, user.version_id AS user_version_id
FROM user]
(Background on this error at: https://sqlalche.me/e/14/f405)
```

**Comment by louking** [comment]
fixed in 2e1d8b2f6468257fae5268801797cfed82ea3c22
