### ISSUE TITLE
BuildError: Could not build url for endpoint 'security.reset_password'

### ISSUE THREAD

**Issue by louking** [louking/mysql-docker#6]
```
> docker exec mysql-docker-shell-1 flask init addsuperadmin example@example.com "Lou King" Lou

Traceback (most recent call last):
  File "/usr/local/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 1063, in main
    cli.main()
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 357, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/app/scripts/__init__.py", line 18, in wrapped
    f(*args, **kwargs)
  File "/app/scripts/init_cli.py", line 70, in addsuperadmin
    send_reset_password_instructions(superadmin_user)
  File "/usr/local/lib/python3.9/site-packages/flask_security/recoverable.py", line 33, in send_reset_password_instructions
    reset_link = url_for_security("reset_password", token=token, _external=True)
  File "/usr/local/lib/python3.9/site-packages/flask_security/utils.py", line 495, in url_for_security
  File "/usr/local/lib/python3.9/site-packages/werkzeug/routing/map.py", line 950, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'security.reset_password' with values ['token']. Did you mean 'security.static' instead?
```

**Comment by louking** [comment]
not sure which change resolved this
