### ISSUE TITLE
BundleError: 'js/jquery-ui-1.13.2.custom/jquery-ui.css' not found in load path

### ISSUE THREAD

**Issue by louking** [louking/mysql-docker#9]
```
ERROR:mysql_docker:Exception on /account/reset/WyJiMDUyZGZkYTQwYzA0ZGJiYWJmNTM4MTkzMzk2NjdjZSIsbnVsbF0.ZMP7IA.toCf_njQSGqD5BZtYVlDi12hamU [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/webassets/bundle.py", line 235, in resolve_contents
    result = ctx.resolver.resolve_source(ctx, item)
  File "/usr/local/lib/python3.9/site-packages/webassets/env.py", line 251, in resolve_source
    return self.search_for_source(ctx, item)
  File "/usr/local/lib/python3.9/site-packages/flask_assets.py", line 192, in search_for_source
    return Resolver.search_for_source(self, ctx, item)
  File "/usr/local/lib/python3.9/site-packages/webassets/env.py", line 180, in search_for_source
    return self.search_load_path(ctx, item)
  File "/usr/local/lib/python3.9/site-packages/webassets/env.py", line 168, in search_load_path
    raise IOError("'%s' not found in load path: %s" % (
OSError: 'js/jquery-ui-1.13.2.custom/jquery-ui.css' not found in load path: ['/app/mysql_docker/static', '/usr/local/lib/python3.9/site-packages/loutilities/tables-assets/static']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/local/lib/python3.9/site-packages/flask_security/decorators.py", line 612, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/flask_security/decorators.py", line 430, in decorated
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/flask_security/views.py", line 605, in reset_password
    return _security.render_template(
  File "/usr/local/lib/python3.9/site-packages/flask_security/utils.py", line 1072, in default_render_template
    return render_template(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/flask/templating.py", line 151, in render_template
    return _render(app, template, context)
  File "/usr/local/lib/python3.9/site-packages/flask/templating.py", line 132, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/usr/local/lib/python3.9/site-packages/loutilities/tables-assets/templates/security/reset_password.jinja2", line 2, in top-level template code
    {% from "security/_macros.html" import render_field_with_errors, render_field %}
  File "/usr/local/lib/python3.9/site-packages/loutilities/tables-assets/templates/bare-layout.jinja2", line 1, in top-level template code
    {% extends "layout-base.jinja2" %}
  File "/usr/local/lib/python3.9/site-packages/loutilities/tables-assets/templates/layout-base.jinja2", line 34, in top-level template code
    {% assets "admin_css" %}
  File "/usr/local/lib/python3.9/site-packages/webassets/ext/jinja2.py", line 187, in _render_assets
    urls = bundle.urls(calculate_sri=True)
  File "/usr/local/lib/python3.9/site-packages/webassets/bundle.py", line 833, in urls
    urls.extend(bundle._urls(new_ctx, extra_filters, *args, **kwargs))
  File "/usr/local/lib/python3.9/site-packages/webassets/bundle.py", line 781, in _urls
    urls.extend(org._urls(
  File "/usr/local/lib/python3.9/site-packages/webassets/bundle.py", line 779, in _urls
    for org, cnt in self.resolve_contents(ctx):
  File "/usr/local/lib/python3.9/site-packages/webassets/bundle.py", line 237, in resolve_contents
    raise BundleError(e)
webassets.exceptions.BundleError: 'js/jquery-ui-1.13.2.custom/jquery-ui.css' not found in load path: ['/app/mysql_docker/static', '/usr/local/lib/python3.9/site-packages/loutilities/tables-assets/static']
```

**Comment by louking** [comment]
copied js files to static directory
